app/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    add_to_cart,
    reduce_quantity_item,
    ProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    AboutView,
    ProductsView,
)

app_name = 'app'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/',
         AboutView.as_view(), name='about'),
    path('products/',
         ProductsView.as_view(), name='products'),
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('reduce-quantity-item/<pk>/',
         reduce_quantity_item, name='reduce-quantity-item'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/',
         PaymentView.as_view(), name='payment'),

]

mvfp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('app.urls', namespace='app')),
    path("admin/", admin.site.urls),
    path("accounts/", include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# https://medium.com/analytics-vidhya/how-to-create-simple-e-commerce-website-with-django-step-1-of-5-42c6cca414c2
# https://medium.com/analytics-vidhya/how-to-create-fully-functional-e-commerce-website-with-django-c95b46973b0
# https://medium.com/analytics-vidhya/how-to-create-fully-functional-e-commerce-website-with-django-997ffaa0f040
# https://medium.com/analytics-vidhya/how-to-create-fully-functional-e-commerce-website-with-django-7205d250e76f
# https://medium.com/analytics-vidhya/how-to-create-a-fully-functional-e-commerce-website-with-django-d4b998bac01

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return super().__str__()+self.name


class Item(models.Model):
    item_name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self) -> str:
        return super().__str__()+self.name

    def get_absolute_url(self):
        return reverse("app:product", kwargs={"pk": self.pk})

    def get_add_to_cart_url(self):
        return reverse("app:add-to-cart", kwargs={"pk": self.pk})

    def get_remove_from_cart_url(self):
        return reverse("app:remove-from-cart", kwargs={
            "pk": self.pk
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class CheckoutAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

templates/about.html
{% extends 'base.html' %} {% block content %}
<!-- Header-->
<header class="py-5">
    <div class="container px-5">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xxl-6">
                <div class="text-center my-5">
                    <h1 class="fw-bolder mb-3">Our mission</h1>
                    <h2>Serve till you can</h2>
                    <p class="lead fw-normal text-muted mb-4">To address the vast healthcare needs of the nation and the world at large. We also aim to become the leading Pharmaceutical Trading Firm and serve all the needs of hospitality services at the best price and delivery team</p>
                    <a class="btn btn-primary btn-lg" href="#scroll-target">Read our story</a>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- About section one-->
<section class="py-5 bg-light" id="scroll-target">
    <div class="container px-5 my-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="../static/img/ppsingh.png" alt="P P Singh" />
            </div>
            <div class="col-lg-6">
                <h2 class="fw-bolder">Our founding</h2>
                <p class="lead fw-normal text-muted mb-0">Forza Pharmaceutical & M.V. Pharmaceutical, a professionally managed pharmaceutical trading firm centrally located at Patparganj Industrial Area, was established in 2016 by Late Shri P.P. Singh, M.Pharma, Retired as Deputy, Commissioner, Food and Drugs Control Department, U.P. Goverment.</p>
                <p class="lead fw-normal text-muted mb-0">Since then we have been serving the nation, day and night, effortlessly cetering to all kinds of pharmaceutical requirements.</p>
            </div>
        </div>
    </div>
</section>
<!-- About section two-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
            <div class="col-lg-6">
                <h2 class="fw-bolder">We Serve Effortlessly</h2>
                <p class="lead fw-normal text-muted mb-0">Due to the pandemic, COVID-19 (2020-2021), the healthcare facilities and medicines have become the need of hour, India, the second largest populated country of the world, has a growing Pharma sector and is changing lives by providing the necessary amenites since many decades.</p>
                <p class="lead fw-normal text-muted mb-0">We, at Forza Pharmaceutical & M.V. Pharmaceutical believe in giving back to the society hence our moto is to <em>Serve till you can</em></p>
            </div>
        </div>
    </div>
</section>
<!-- Team members section-->
<section class="py-5 bg-light">
    <div class="container px-5 my-5">
        <div class="text-center">
            <h2 class="fw-bolder">Our team</h2>
            <p class="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
        </div>
        <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
            <div class="col mb-5 mb-5 mb-xl-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="../static/img/mom.png" alt="Dr Sanghmitra" />
                    <h5 class="fw-bolder">Dr. Sanghmitra</h5>
                    <div class="fst-italic text-muted">Co-Founder &amp; CEO</div>
                </div>
            </div>
            <div class="col mb-5 mb-5 mb-xl-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="../static/img/vidushi.png" alt="Vidushi" />
                    <h5 class="fw-bolder">Vidushi Kain</h5>
                    <div class="fst-italic text-muted">CFO & CIO</div>
                </div>
            </div>
            <div class="col mb-5 mb-5 mb-sm-0">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="../static/img/medha.png" alt="Medhavi" />
                    <h5 class="fw-bolder">Medhavi</h5>
                    <div class="fst-italic text-muted">CMO</div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="text-center">
                    <img class="img-fluid rounded-circle mb-4 px-4" src="../static/img/vidushi.png" alt="Vidushi" />
                    <h5 class="fw-bolder">Vidushi Kain</h5>
                    <div class="fst-italic text-muted">CTO</div>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container px-5 my-5">
        <div class="text-center">
            <h2 class="fw-bolder">Our Sponsors</h2>
        </div>
        <div class="row">
            <div class="col">
                <ul>
                    <li>Aculife</li>
                    <li>Zee laboratories</li>
                    <li>Radico</li>
                    <li>Amanta</li>
                </ul>
            </div>
            <div class="col">
                <ul>
                    <li>Hopecure Lifecare</li>
                    <li>Romsons</li>
                    <li>Dispovan</li>
                    <li>Nipro</li>
                </ul>
            </div>
            <div class="col">
                <ul>
                    <li>B Braun</li>
                    <li>Pretty Petals</li>
                    <li>Sunrise Pharma</li>
                    <li>Enema</li>
                </ul>
            </div>
        </div>
        </div>
        
</section>
</main>
{% endblock content %}

templates/base.html
{% load static %}

{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>MV&F Pharmaceutical</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
</head>

<body class="d-flex flex-column h-100">
  <main class="flex-shrink-0">
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
      <!-- Brand -->
      <a class="navbar-brand" href="/">F & M.V. Pharmaceutical</a>
      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="nav ms-auto mb-2 mb-lg-0">
          <a class="nav-item nav-link active mr-2" href="/">Home</a>
          <a class="nav-item nav-link " href={% url 'app:products' %}>Products</a>
          <a class="nav-item nav-link " href={% url 'app:about' %}>About Us</a>
          {% if user.is_authenticated %}         
              <a href="{% url 'app:order-summary' %}" class="nav-link ">
              {% if request.user|cart_item_count != 0 %}
                <span class="badge badge-primary z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              {% endif %}
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block">Cart</span>
              </a>
              <a class="nav-item nav-link ">Hi {{ user.username }}!</a>
              <a class="nav-item nav-link " href="{% url 'logout' %}"> Logout</a>
          {% else %}
              <a class="nav-item nav-link " href="{% url 'login' %}"> Login/Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  <!-- Navbar -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
      </div>
    {% block content %}
    {% endblock content %}
  </main>
    {% include "footer.html" %}

    {% include "script.html" %}

    {% block extra_script %}
    {% endblock extra_script %}
</body>
</html>

templates/footer.html
<!--Footer-->
<footer class="bg-dark py-4 mt-auto">
  <div class="container px-5">
      <div class="row align-items-center justify-content-between flex-column flex-sm-row">
          <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Trinly LLC 2023</div></div>
          <div class="col-auto">
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
              <i class="fa-brands fa-facebook-f mx-3"></i>
            </a>      
            <a href="https://twitter.com/MDBootstrap" target="_blank">
              <i class="fa-brands fa-twitter mx-3"></i>
            </a>
            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
              <i class="fa-brands fa-youtube mx-3"></i>
            </a>
            <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
              <i class="fa-brands fa-google-plus-g mx-3"></i>
            </a>
            <a href="https://dribbble.com/mdbootstrap" target="_blank">
              <i class="fa-brands fa-dribbble mx-3"></i>
            </a>
            <a href="https://pinterest.com/mdbootstrap" target="_blank">
              <i class="fa-brands fa-pinterest mx-3"></i>
            </a>
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
              <i class="fa-brands fa-github mx-3"></i>
            </a>
            <a href="http://codepen.io/mdbootstrap/" target="_blank">
              <i class="fa-brands fa-codepen mx-3"></i>
            </a>
          </div>
            <div class="col-auto">
            <a class="link-light small" href="#!">Privacy</a>
            <span class="text-white mx-1">&middot;</span>
            <a class="link-light small" href="#!">Terms</a>
            <span class="text-white mx-1">&middot;</span>
            <a class="link-light small" href="#!">Contact</a>
          </div>
      </div>
  </div>
</footer>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-5">
            <div class="row gx-5 align-items-center justify-content-center">
                <div class="col-lg-8 col-xl-7 col-xxl-6">
                    <div class="my-5 text-center text-xl-start">
                        <h1 class="display-5 fw-bolder  text-white mb-2">Forza & M. V. Pharmaceutical</h1>
                        <p class="lead fw-normal  text-white-50 mb-4">
                            Forza & M.V. Pharmaceutical, a professionally managed pharmaceutical trading firm serving the nation effortlessly catering to all kind of pharmaceutical requirements.
                        </p>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Contact Us</a>
                            <a class="btn btn-outline-light btn-lg px-4" href={% url 'app:about' %}>Learn More</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                    <img class="img-fluid rounded-3 my-5"
                         src="https://dummyimage.com/600x400/343a40/6c757d"
                         alt="..."/>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="container">
            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded my-3">
                <!-- Navbar brand -->
              <span class="navbar-brand ms-2">Categories:</span>
                <!-- Collapse button -->
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#searchNav"
                        aria-controls="searchNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="searchNav">
                    <!-- Links -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">
                                All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        {% for category in categories %}
                            <li class="nav-item">
                                <a href="#" class="nav-link">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    <!-- Links -->
                    <form class="d-flex">
                        <input class="form-control me-2"
                               type="search"
                               placeholder="Search"
                               aria-label="Search"/>
                        <button class="btn btn-outline-success me-2" type="submit">Search</button>
                    </form>
                </div>
            </nav>
            <!--/.Navbar-->
            <!--Section: Products v.3-->
            <section class="text-center mb-4">
                <!--Grid row-->
                <div class="row wow fadeIn">
                    {% for item in object_list %}
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4">
                            <!--Card-->
                            <div class="card">
                                <!--Card image-->
                                <div class="view overlay">
                                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                         class="card-img-top"
                                         alt=""/>
                                    <a href="{{ item.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card image-->
                                <!--Card content-->
                                <div class="card-body text-center">
                                    <!--Category & Title-->
                                    <a href="" class="grey-text">
                                        <h5>{{ item.get_category_display }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.item_name }}
                                                <span class="badge badge-pill {% if item.get_label_display == 'New' %} danger-color {% else %} primary-color {% endif %}">{{ item.get_label_display }}</span
                                                    >
                                                </a>
                                            </strong>
                                        </h5>
                                        <h4 class="font-weight-bold blue-text">
                                            <strong>$
                                                {% if item.discount_price %}
                                                    {{ item.discount_price }}
                                                {% else %}
                                                    {{ item.price }}
                                                {% endif %}
                                            </strong>
                                        </h4>
                                    </div>
                                    <!--Card content-->
                                </div>
                                <!--Card-->
                            </div>
                            <!--Grid column-->
                        {% endfor %}
                    </div>
                    <!--Grid row-->
                </section>
                <!--Section: Products v.3-->
                <!--Pagination-->
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination pg-blue">
                        <!--Arrow left-->
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="#">1
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">4</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">5</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!--Pagination-->
            </div>
        </main>
        <!--Main layout-->
    {% endblock content %}

templates/order_summary.html
{% extends 'base.html' %} {% block content %}

<main>
  <div class="container">
    <div class="table-responsive text-nowrap">
      <h3>
        <strong>Your Cart</strong>
      </h3>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.item_name }}</td>
            <td>
              {% if order_item.item.discount_price %}
              <del>${{ order_item.item.price}}</del>
              ${{ order_item.item.discount_price }} {% else %} ${{
              order_item.item.price}} {% endif %}
            </td>
            <td>
              <a href="{% url 'app:reduce-quantity-item' order_item.item.pk %}"
                ><i class="fas fa-minus mr-2"></i
              ></a>
              {{ order_item.quantity }}
              <a href="{% url 'app:add-to-cart' order_item.item.pk %}"
                ><i class="fas fa-plus ml-2"></i
              ></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
              ${{order_item.get_discount_item_price }}
              <span class="badge badge-success"
                >Saved ${{ order_item.get_amount_saved }}</span
              >
              {% else %} ${{ order_item.get_total_item_price}} {% endif %}
              <a href="{% url 'app:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
              </a>
            </td>
          </tr>

          {% empty %}
          <tr>
            <td colspan="5">Your Cart Empity</td>
          </tr>

          <tr>
            <td colspan="5">
              <a href="/" class="btn btn-primary float-right"
                >Continue Shopping</a
              >
            </td>
          </tr>

          {% endfor %} {% if object.get_total_price %}
          <tr>
            <td colspan="4"><b>Total Order Price</b></td>
            <td>${{ object.get_total_price }}</td>
          </tr>
          <tr>
            <td colspan="5">
              <a
                href="{% url 'app:checkout' %}"
                class="btn btn-warning float-right ml-2"
                >Checkout</a
              >
              <a href="/" class="btn btn-primary float-right"
                >Continue Shopping</a
              >
            </td>
          </tr>

          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock content %}

templates/product.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{ object.get_label_display }}</span>
              </a>
            </div>

            <p class="lead">

            {% if object.discount_price %}
              <span class="mr-1">
              <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
            {% else %}
             <span>${{ object.price }}</span>
            {% endif %}

            </p>

            <p class="lead font-weight-bold">{{ object.item_name }}</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From cart
                <i class="fas fa-trash ml-1"></i>
            </a>
           

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/products.html
{% extends 'base.html' %} {% block content %}

<section class="py-5">
    <div class="container">
        <div class="row text-center my-5">
            <h1 class="fw-bolder mb-3">Our Products</h1>
        </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Price</th>
                            <th scope="col">Discounted Price</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{item.item_name}}</td>
                            <td>{{item.category.name}}</td>
                            <td>{{item.price}}</td>
                            <td>{{item.discount_price}}</td>
                            <td><button class="btn btn-primary">Add to Cart</button></td>
                        </tr>  
                        {% endfor %}
                    </tbody>
                </table>
            </div>        
    </div>
</section>


{% endblock content %}